# Assignment_3:

Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def division():
    """Zero division method, capturing the exception"""
    try:
        number1 = int(input('Enter a number: '))
        number2 = int(input('Enter another number: '))
        result = number1 / number2
    except:
        print('You cannot divide by 0.')
    else:
        print('The division is:', result)


division()

Enter a number: 5
Enter another number: 0
You cannot divide by 0.


Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [2]:
subjects = ["Americans", "Indians"]
verbs = ["play", "watch"]
objects = ["Baseball", "Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(f"{i} {j} {k}.")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [3]:
import numpy as np


def square(col, increasing):
    output = np.vander(input_vector, col, increasing)
    print(f'The Output is: \n{output}')
    print('-' * 30)


input_vector = np.array([1, 2, -1, 4, 5])
square(3, False)
square(3, True)

The Output is: 
[[ 1  1  1]
 [ 4  2  1]
 [ 1 -1  1]
 [16  4  1]
 [25  5  1]]
------------------------------
The Output is: 
[[ 1  1  1]
 [ 1  2  4]
 [ 1 -1  1]
 [ 1  4 16]
 [ 1  5 25]]
------------------------------
